apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    app: {{ include "n8n.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "n8n.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "n8n.name" . }}
    spec:
      containers:
        - name: n8n
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: EXECUTIONS_MODE
              value: "{{ .Values.config.executions.mode }}"
          ports:
            - containerPort: 5678
