{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}-worker
spec:
  replicas: {{ .Values.worker.count }}
  selector:
    matchLabels:
      app: {{ include "n8n.name" . }}-worker
  template:
    metadata:
      labels:
        app: {{ include "n8n.name" . }}-worker
    spec:
      containers:
        - name: n8n-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: N8N_WORKER
              value: "true"
            - name: EXECUTIONS_PROCESS
              value: "main"
            - name: EXECUTIONS_MODE
              value: "{{ .Values.config.executions.mode }}"
          resources: {}
{{- end }}
